In [2]:
import pandas as pd

In [3]:
# 2 types of data structure exists in pandas
# 1- series
# 2- dataframe

In [4]:
# series- 1 dimensional labled array
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))

# index 
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
# index and labled are different means index tell the position of th element 
# but labeled use is named index, column that are print in the output before 
# the real value is labled that are by default == index value
s=pd.Series([23,4,5,67], index=["Adam", "Eve", "Bob", "Charlie"])
print(s)
# here we change the labled name
# and now we can access our data using lable value and index value both 
print(s["Adam"])
# print(s[0])
print(s.index)

Adam       23
Eve         4
Bob         5
Charlie    67
dtype: int64
23
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [6]:
# properties
import pandas as pd
# homogeneous
s=pd.Series([23,4,5,"abc"], index=["Adam", "Eve", "Bob",12])
print(s)# datatypes of all value are same 
# we can perform vectorization
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)
# mutable value
s1[0]=100
print(s1)
# immutable size
changed_s1=s1.drop(2)
print(s1)# size of s1 not affected value change but in changed_s1 means if we want to add or drop an element than we need to creat another series 
print(changed_s1)
# handle missing value with NaN

Adam     23
Eve       4
Bob       5
12      abc
dtype: object
0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
3      4
4      5
dtype: int64

In [7]:
# second data structure 
# data frame - Table form
# many ways to create dataFrame
# 1st way
info={
    "Name":["Adam","Eve","Bob","jack"],
    "CGPA":[9.3, 8.4, 6.4, 8.5],
    "Age":[23, 24, 19, 20]
}
df=pd.DataFrame(info)
print(df, type(df))
print(df.index)# print the lable for row value
print(df.columns)# print the lable for columns
df

   Name  CGPA  Age
0  Adam   9.3   23
1   Eve   8.4   24
2   Bob   6.4   19
3  jack   8.5   20 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='object')

   Name  CGPA  Age
0  Adam   9.3   23
1   Eve   8.4   24
2   Bob   6.4   19
3  jack   8.5   20

In [8]:
# 2nd way
df=pd.DataFrame([["adam",23],["eve",24],["bob",19],["jack",20]], columns=["name", "age"])
print(df)
df

   name  age
0  adam   23
1   eve   24
2   bob   19
3  jack   20

   name  age
0  adam   23
1   eve   24
2   bob   19
3  jack   20

In [9]:
# 3rd ways
import numpy as np
np_arr=np.array([[1, 2, 3], [4, 5, 6]])
df=pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
# usage of csv
df=pd.read_csv("employee_data.csv")
# print(df, type(df))
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [11]:
# json data
df=pd.read_json("data1.json")
print(df, type(df))
# for excel - read_excel
# for sql - read_sql

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [12]:
# data frame Methods
df=pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [13]:
# head- print initial 5 
df.head()
df.head(2)# print first 2 value

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000

In [14]:
# tail -print last 5 value
df.tail()
df.tail(2)# print last 2 value

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [15]:
# sample
df.sample()# any random row 
df.sample(2)# any random 2 row

   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000
5   6  Frank   29    Finance   50000

In [16]:
# info
df.info() # summary of our data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [17]:
df.shape # print no of rows and columns in tuple format

(10, 5)

In [18]:
df.describe() # give some useful informations about our data for numerical value
# 25% means 25% people have leaas than salary of "salary data"

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [19]:
#columns
df.columns #p print columns values

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [20]:
df.nunique() # print no of unique rows in column

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [21]:
df=pd.read_csv("AQIdata.csv")

df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [22]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [23]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [24]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [25]:
# accessing row value
# printing single column
df["country"]
# printing multiple column
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [26]:
# Accessing rows value
# label base access
df.loc[2]
df.loc[0:2] # start idx : end idx (inclusive)
# index base
df.iloc[2]
df.iloc[0:2] #start idx : end idx (exclusive)

# Accessing row and column together
# for label base
df.loc[0:2, ["city", "aqi"]]
df.loc[0:2, ["country", "city", "latitude", "longitude"]]
df.iloc[0:3,2]# "2" is index of city
df.iloc[0:3, 1:5]# row index range, column index range
# cell
# selecting single numerical value
df.at[0, "city"]
df.iat[0, 2]
# pandas provide view of data like numpy
# means
cities=df["city"]
cities[0]="New york"
# to avoid this mistake
cities=df["city"].copy()
cities[0]="Mumbai"# copy
cities
# now when we print cities value its change but in orginal data the value of city remains same

C:\Users\lenovo\AppData\Local\Temp\ipykernel_20380\2460618761.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cities[0]="New york"

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [27]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New york,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [28]:
# filtering
# single condition
df[ df["aqi"] > 100]

# Multiple condition - use &(and) |(or)  ^(not)
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
# simple pattern - when temperature is low aqi is low in maximum city
# if we want to print only limited columm
aqi_data=df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi", "temperature"]]
# pandas not change label value after filtering

aqi_data.iloc[0]
# aqi_data.loc[0] # show an error because label 0 are not exist

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New york,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [5]:
# Query method for data filtering 
# rule for query()
# expression as a string
# column based reference
# backticks for column_name with space or special chars
# operators ( &, |, ~, >=, >, ==, etc.)
df.query("aqi > 100")
# @ to reference python variable 
aqi_var=100
df.query("aqi > @aqi_var & temperature > 30")[["city", "aqi"]]
# chain comparison
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
"""Note - query returns copy of filter data not view"""
# dont nedd to remeber all this copy and view things for the shake of simplicity 
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]].copy()

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [21]:
"""Data cleaning"""
import pandas as pd
# handling missing value
df=pd.read_csv("raw_data.csv")
df.isnull() # detect NaN value
df.isna() # both are same
df.isnull().sum() # number of missing value inn every column
df.dropna() # drop all the row where any nan value exist 
df.dropna(axis=1) # drop all the column where any nan value exist 
df.fillna(0) # all NaN value will repalace by 0 
df.fillna(100) # all NaN value will replace by 100
age_mean=df["age"].mean()
cleaned_data = df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data
# ffill() stands for forward fill
df.ffill() # all nan value replace by the value before the nan value
df.bfill() # all nan value replace by the value after the nan value

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [22]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [32]:
# handle duplicate value
df.duplicated()
# can check duplicate value for column wise, row wise, and set of column and row wise
df["country"].duplicated()
df[["country", "gender"]].duplicated()
df.drop_duplicates() # drop all the duplicate value
"""Note:- this changes not reflects in original data to do this we need to copy dat and then proceed or 
we can use "implace=True" attribute"""
df2=df.copy() # prefered may be we need some times to use our original data show if we have copy of it then its simple for us
df.drop_duplicates(inplace=True) # chnnges show in the original data

In [33]:
df # changes show there

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [49]:
# handling data types & date-time
df.dtypes

df2=df.copy()
df2=df2.fillna(0)
df3=df2["age"].astype("int64").copy()
# astype(new__type) use to convert data types
df2.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [55]:
# date_type
aqi_data=pd.read_csv("AQIdata.csv")
aqi_data["timestamp"].dtype
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype
# this data transsorm in date type
# 'o' stands for object

dtype('<M8[ns]')

In [53]:
# creating datetime data
data_str=pd.Series([pd.to_datetime("2025-12-31")])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType

In [66]:
# handle strings
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("india",case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object